import type { MetadataRoute } from 'next'

import { SITE_NAME, SITE_SHORT_NAME, SITE_TAGLINE, SITE_URL } from '@/lib/constants'

/**
 * Web app manifest.
 *
 * This is what turns the site into an installable app on Android, iOS and
 * desktop: a home-screen icon, a splash colour, a standalone window without
 * browser chrome, and shortcuts straight into membership, verification and
 * events. Next serves it at `/manifest.webmanifest` and links it from every
 * page, so no manual `<link>` is needed.
 *
 * The icons are generated by `scripts/build-logo-assets.py`; the 512 and 192
 * entries are the two sizes Android asks for, and `maskable` is what keeps the
 * crest from being cropped into a circle badly on Android's adaptive icons.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} | ${SITE_SHORT_NAME}`,
    short_name: SITE_SHORT_NAME,
    description:
      `${SITE_SHORT_NAME} — ${SITE_TAGLINE} A national, non-partisan platform for youth leadership, ` +
      'parliamentary engagement, public policy and international participation.',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui'],
    orientation: 'any',
    background_color: '#04110e',
    theme_color: '#0b3d2e',
    lang: 'en',
    dir: 'ltr',
    categories: ['education', 'government', 'social', 'news'],
    icons: [
      {
        src: '/images/pypc-emblem-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any'
      },
      {
        src: '/images/pypc-emblem-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any'
      },
      {
        // Safe-zone padded, so Android's circular/squircle masks never clip the crest.
        src: '/images/pypc-emblem-maskable-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable'
      }
    ],
    shortcuts: [
      { name: 'Become a member', url: '/membership' },
      { name: 'Verify a certificate', url: '/verify' },
      { name: 'Events', url: '/events' },
      { name: 'IMUN 2027', url: '/conferences/imun-2027' }
    ],
    screenshots: [
      {
        src: '/images/pypc-emblem-512.png',
        sizes: '512x512',
        type: 'image/png'
      }
    ]
  }
}
