import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  Ban,
  BookOpen,
  BookOpenCheck,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CircleCheck,
  LayoutList,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Clock,
  CreditCard,
  Download,
  Eye,
  ExternalLink,
  FileCheck2,
  FileText,
  Filter,
  Fingerprint,
  Globe2,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Pencil,
  Phone,
  Plus,
  Printer,
  Quote,
  RefreshCw,
  RotateCcw,
  Scale,
  ScrollText,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  UserRound,
  Users,
  UsersRound,
  X,
  type LucideIcon
} from 'lucide-react'

/**
 * Central icon registry. Pages and data files reference icons by string name so
 * database-driven content can choose an icon without shipping component code.
 */
export const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  Ban,
  BookOpen,
  BookOpenCheck,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CircleCheck,
  LayoutList,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDollarSign,
  Clock,
  CreditCard,
  Download,
  Eye,
  ExternalLink,
  FileCheck2,
  FileText,
  Filter,
  Fingerprint,
  Globe2,
  GraduationCap,
  HeartHandshake,
  KeyRound,
  Landmark,
  LayoutDashboard,
  Leaf,
  LifeBuoy,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageSquare,
  Pencil,
  Phone,
  Plus,
  Printer,
  Quote,
  RefreshCw,
  RotateCcw,
  Scale,
  ScrollText,
  Search,
  Send,
  ShieldAlert,
  ShieldCheck,
  Target,
  Ticket,
  Trash2,
  TrendingUp,
  UserRound,
  Users,
  UsersRound,
  X
}

export type IconName = keyof typeof iconRegistry

export function Icon({
  name,
  className,
  size = 20,
  strokeWidth = 2
}: {
  name: string
  className?: string
  size?: number
  strokeWidth?: number
}) {
  const Component = iconRegistry[name] ?? CircleCheck
  return <Component className={className} size={size} strokeWidth={strokeWidth} />
}
