// Open photography attribution and placement registry.
export const sitePhotos = [
  {
    "key": "parliament-hero",
    "src": "/images/editorial/parliament-hero.webp",
    "alt": "Parliament House in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Parliament_House,_Islamabad_by_Usman_Ghani.jpg",
    "author": "Usman.pg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Parliament House, Islamabad by Usman Ghani.jpg",
    "width": 1746,
    "height": 1164
  },
  {
    "key": "pakistan-monument",
    "src": "/images/editorial/pakistan-monument.webp",
    "alt": "Pakistan Monument illuminated at blue hour in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Blue_Hour_at_Pakistan_Monument.jpg",
    "author": "Muhammad Ashar",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Blue Hour at Pakistan Monument.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "diplomacy",
    "src": "/images/editorial/diplomacy.webp",
    "alt": "United Nations General Assembly hall",
    "source": "https://commons.wikimedia.org/wiki/File:UN_General_Assembly_hall.jpg",
    "author": "Patrick Gruban, cropped and downsampled by Pine",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "originalTitle": "UN General Assembly hall.jpg",
    "width": 1920,
    "height": 1191
  },
  {
    "key": "learning",
    "src": "/images/editorial/learning.webp",
    "alt": "Central library at Quaid i Azam University in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:C.L_Quaid-e-Azam_University_Islamabad.jpg",
    "author": "Izharkasi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "C.L Quaid-e-Azam University Islamabad.jpg",
    "width": 1280,
    "height": 960
  },
  {
    "key": "cultural-exchange",
    "src": "/images/editorial/cultural-exchange.webp",
    "alt": "Historic architecture in Saidpur village, Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Saidpur_1.jpg",
    "author": "Zaidimazhar1214",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Saidpur 1.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "pakistan-student-dialogue",
    "src": "/images/editorial/pakistan-student-dialogue.webp",
    "alt": "Pakistani students in a cultural exchange discussion at Allama Iqbal Open University in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Pakistan-U.S._Student_Exchange_Program_2011_(5959529887).jpg",
    "author": "USAID Pakistan",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:Pakistan-U.S._Student_Exchange_Program_2011_(5959529887).jpg",
    "originalTitle": "Pakistan-U.S. Student Exchange Program 2011 (5959529887).jpg",
    "width": 1280,
    "height": 850
  },
  {
    "key": "assembly",
    "src": "/images/editorial/assembly.webp",
    "alt": "Delegates attending the United Nations General Assembly in 2025",
    "source": "https://commons.wikimedia.org/wiki/File:23.09.2025_%E2%80%93_Abertura_do_Debate_Geral_da_80.%C2%AA_Sess%C3%A3o_Ordin%C3%A1ria_da_Assembleia_Geral_das_Na%C3%A7%C3%B5es_Unidas_-_54807092026.jpg",
    "author": "Lula Oficial",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "23.09.2025 – Abertura do Debate Geral da 80.ª Sessão Ordinária da Assembleia Geral das Nações Unidas - 54807092026.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "pakistan-earth-day",
    "src": "/images/editorial/pakistan-earth-day.webp",
    "alt": "Tree planting to mark Earth Day 2013 with the MEPCO chief executive in Pakistan",
    "source": "https://commons.wikimedia.org/wiki/File:USAID_celebrates_Earth_Day_2013_(13302524105).jpg",
    "author": "USAID Pakistan",
    "license": "Public domain",
    "licenseUrl": "https://commons.wikimedia.org/wiki/File:USAID_celebrates_Earth_Day_2013_(13302524105).jpg",
    "originalTitle": "USAID celebrates Earth Day 2013 (13302524105).jpg",
    "width": 1280,
    "height": 850
  },
  {
    "key": "pakistan-computer-lab",
    "src": "/images/editorial/pakistan-computer-lab.webp",
    "alt": "Computer laboratory at Government High School Wagh in Jhelum district, Pakistan",
    "source": "https://commons.wikimedia.org/wiki/File:Computer_lab_ghs_wagh.JPG",
    "author": "Aqeel 755",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Computer lab ghs wagh.JPG",
    "width": 1280,
    "height": 960
  },
  {
    "key": "institutional-visit",
    "src": "/images/editorial/institutional-visit.webp",
    "alt": "Tree lined Ataturk Avenue in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Ataturk_Avenue_-_Islamabad.JPG",
    "author": "Obaid747",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Ataturk Avenue - Islamabad.JPG",
    "width": 1280,
    "height": 853
  },
  {
    "key": "senate",
    "src": "/images/editorial/senate.webp",
    "alt": "Parliament House in Islamabad illuminated at night",
    "source": "https://commons.wikimedia.org/wiki/File:Parliament_House_Islamabad.jpg",
    "author": "Mhtoori",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Parliament House Islamabad.jpg",
    "width": 1920,
    "height": 1281
  },
  {
    "key": "governance",
    "src": "/images/editorial/governance.webp",
    "alt": "Pakistan Secretariat buildings in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Pak_Secretariat_buildings,Islamabad_by_Usman_Ghani.jpg",
    "author": "Usman.pg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Pak Secretariat buildings,Islamabad by Usman Ghani.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "climate",
    "src": "/images/editorial/climate.webp",
    "alt": "Forested landscape along Trail 3 in the Margalla Hills",
    "source": "https://commons.wikimedia.org/wiki/File:Trail_3_Margalla_Hills_Islamabad.jpg",
    "author": "Khaanimraan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Trail 3 Margalla Hills Islamabad.jpg",
    "width": 1280,
    "height": 716
  },
  {
    "key": "technology",
    "src": "/images/editorial/technology.webp",
    "alt": "Virtual reality headset and computer workstation",
    "source": "https://commons.wikimedia.org/wiki/File:VR_Workstation.jpg",
    "author": "Mbrickn",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "VR Workstation.jpg",
    "width": 1920,
    "height": 1440
  },
  {
    "key": "human-rights",
    "src": "/images/editorial/human-rights.webp",
    "alt": "Eleanor Roosevelt holding the Universal Declaration of Human Rights",
    "source": "https://commons.wikimedia.org/wiki/File:Eleanor_Roosevelt_UDHR.jpg",
    "author": "FDR Presidential Library & Museum",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "originalTitle": "Eleanor Roosevelt UDHR.jpg",
    "width": 1280,
    "height": 1005
  },
  {
    "key": "entrepreneurship",
    "src": "/images/editorial/entrepreneurship.webp",
    "alt": "Participants networking at an entrepreneurship workshop",
    "source": "https://commons.wikimedia.org/wiki/File:Computer_industry_entrepreneur_workshop.jpg",
    "author": "Dell's Official Flickr Page",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "originalTitle": "Computer industry entrepreneur workshop.jpg",
    "width": 1280,
    "height": 852
  },
  {
    "key": "leadership",
    "src": "/images/editorial/leadership.webp",
    "alt": "Tulane University students volunteering in an environmental project",
    "source": "https://commons.wikimedia.org/wiki/File:Tulane_University_Environmental_Action_League,_New_Orleans,_February_2011.jpg",
    "author": "Tulane Public Relations",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "originalTitle": "Tulane University Environmental Action League, New Orleans, February 2011.jpg",
    "width": 1280,
    "height": 852
  },
  {
    "key": "justice",
    "src": "/images/editorial/justice.webp",
    "alt": "Supreme Court of Pakistan in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Supreme_Court_of_Pakistan,_Islamabad_by_Usman_Ghani.jpg",
    "author": "Usman.pg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Supreme Court of Pakistan, Islamabad by Usman Ghani.jpg",
    "width": 1280,
    "height": 860
  },
  {
    "key": "global-forum",
    "src": "/images/editorial/global-forum.webp",
    "alt": "Panoramic view of the United Nations General Assembly hall",
    "source": "https://commons.wikimedia.org/wiki/File:Panorama_of_the_United_Nations_General_Assembly,_Oct_2012.jpg",
    "author": "Spiff",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Panorama of the United Nations General Assembly, Oct 2012.jpg",
    "width": 1280,
    "height": 530
  },
  {
    "key": "islamabad",
    "src": "/images/editorial/islamabad.webp",
    "alt": "Faisal Mosque and the green landscape of Islamabad after rain",
    "source": "https://commons.wikimedia.org/wiki/File:FaisalMosqueAfterRain.jpg",
    "author": "Moiz.ismaili",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "FaisalMosqueAfterRain.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "forest-restoration",
    "src": "/images/editorial/forest-restoration.webp",
    "alt": "Young trees protected during forest restoration in the Black Forest",
    "source": "https://commons.wikimedia.org/wiki/File:Plastic_tree_protectors_in_the_Schwarzwald.jpg",
    "author": "Robbie Morrison (RobbieIanMorrison)",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "originalTitle": "Plastic tree protectors in the Schwarzwald.jpg",
    "width": 1920,
    "height": 1280
  },
  {
    "key": "international-law",
    "src": "/images/editorial/international-law.webp",
    "alt": "Grand Hall of Justice at the Peace Palace in The Hague",
    "source": "https://commons.wikimedia.org/wiki/File:Grand_Hall_de_Justice_de_Palais_de_La_Paix_%C3%A0_La_Haye_Pays-Bas.jpg",
    "author": "Lybil BER",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Grand Hall de Justice de Palais de La Paix à La Haye Pays-Bas.jpg",
    "width": 1280,
    "height": 853
  },
  {
    "key": "civic-institutions",
    "src": "/images/editorial/civic-institutions.webp",
    "alt": "Constitution Avenue and civic institutions in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Constitution_Avenue.jpg",
    "author": "Zacharie Grossen",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "originalTitle": "Constitution Avenue.jpg",
    "width": 1280,
    "height": 852
  },
  {
    "key": "urban-nature",
    "src": "/images/editorial/urban-nature.webp",
    "alt": "Pavilion and green space at Fatima Jinnah Park in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Fatima_Jinnah_Park_baradri_By_@ibneazhar_(62).jpg",
    "author": "Ibnazhar",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Fatima Jinnah Park baradri By @ibneazhar (62).jpg",
    "width": 1280,
    "height": 960
  },
  {
    "key": "jinnah-venue",
    "src": "/images/editorial/jinnah-venue.webp",
    "alt": "Jinnah Convention Centre in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Jinnah%20Convention%20Centre%2CIslamabad%20by%20Usman%20Ghani.jpg",
    "author": "Usman.pg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Jinnah Convention Centre,Islamabad by Usman Ghani.jpg",
    "width": 1280,
    "height": 854
  },
  {
    "key": "friendship-venue",
    "src": "/images/editorial/friendship-venue.webp",
    "alt": "Pakistan China Friendship Center in Islamabad",
    "source": "https://commons.wikimedia.org/wiki/File:Standing%20between%20Pak-china%20center%20%26%20Crescent%20and%20Star%20monument.jpg",
    "author": "Miiqbal",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "originalTitle": "Standing between Pak-china center & Crescent and Star monument.jpg",
    "width": 1280,
    "height": 960
  }
] as const

export function getSitePhoto(src: string) {
  return sitePhotos.find(photo => photo.src === src)
}

export const programmePhotos: Record<string, string> = {
  'youth-parliament': '/images/editorial/governance.webp',
  'climate-action': '/images/editorial/climate.webp',
  'ai-technology': '/images/editorial/technology.webp',
  'human-rights': '/images/editorial/human-rights.webp',
  'entrepreneurship': '/images/editorial/entrepreneurship.webp',
  'leadership-fellowship': '/images/editorial/leadership.webp',
  'justice-reform': '/images/editorial/justice.webp'
}
