
import { displayContent } from '@/lib/display-content'
import type { Metadata } from 'next'
import Link from 'next/link'
import {
  AlertTriangle,
  CheckCircle2,
  Database,
  FileText,
  HardDrive,
  Mail,
  RefreshCw,
  Server,
  ShieldCheck,
  Wallet,
  XCircle
} from 'lucide-react'
import { Card } from '@/components/ui/card'
import { collectSystemHealth, type HealthState } from '@/lib/health'
import { formatDateTime } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'System status',
  description:
    'Live connectivity status for the Pakistan Youth Parliamentary Council platform: database, email delivery, private document storage, payment gateways and institutional assets.'
}

export const dynamic = 'force-dynamic'

const STATE_STYLE: Record<HealthState, { badge: string; dot: string; label: string; Icon: typeof CheckCircle2 }> = {
  ok: {
    badge: 'border-emerald-200 bg-emerald-50 text-emerald-800',
    dot: 'bg-emerald-500',
    label: 'Operational',
    Icon: CheckCircle2
  },
  warn: {
    badge: 'border-amber-200 bg-amber-50 text-amber-900',
    dot: 'bg-amber-500',
    label: 'Needs attention',
    Icon: AlertTriangle
  },
  fail: {
    badge: 'border-rose-200 bg-rose-50 text-rose-700',
    dot: 'bg-rose-500',
    label: 'Not working',
    Icon: XCircle
  }
}

const ICONS: Record<string, typeof Database> = {
  database: Database,
  email: Mail,
  storage: HardDrive,
  payments: Wallet,
  assets: FileText
}

/**
 * Public connectivity page.
 *
 * Every panel below is generated by a real query, a real file-system probe or a
 * real configuration read at request time — nothing on this page is hard-coded,
 * which is exactly what makes it useful when something does go wrong.
 */
export default async function StatusPage() {
  const report = await collectSystemHealth()
  const overall = STATE_STYLE[report.overall]

  return (
    <div className="surface-page">
      <section className="container py-14">
        <div className="flex flex-wrap items-start justify-between gap-6">
          <div className="max-w-3xl">
            <p className="kicker-gold flex items-center gap-2">
              <Server size={14} /> Connectivity
            </p>
            <h1 className="mt-3 text-3xl font-extrabold tracking-tight text-slate-900 sm:text-4xl">
              System status
            </h1>
            <p className="mt-3 text-base leading-7 text-slate-600">
              This page is generated on every request from the running application: the database is
              queried, the storage folder is probed, the email transport and payment adapters are read
              from the live configuration. It contains no secrets and no personal data, only statuses
              and counts.
            </p>
          </div>

          <div className={`flex items-center gap-3 rounded-2xl border px-5 py-4 ${overall.badge}`}>
            <overall.Icon size={20} />
            <div>
              <p className="text-[11px] font-bold uppercase tracking-[0.16em] opacity-80">Overall</p>
              <p className="text-lg font-extrabold">{displayContent(overall.label)}</p>
            </div>
          </div>
        </div>

        <div className="mt-4 flex flex-wrap items-center gap-x-6 gap-y-2 text-xs font-semibold text-slate-500">
          <span className="flex items-center gap-1.5">
            <RefreshCw size={13} /> Checked {displayContent(formatDateTime(report.generatedAt))}
          </span>
          <span>Reload the page for a fresh reading.</span>
          <Link
            href="/api/status"
            className="font-bold text-primary underline decoration-gold-300 underline-offset-2"
          >
            Machine readable JSON (for uptime monitors)
          </Link>
        </div>

        <div className="mt-10 grid gap-5 lg:grid-cols-2">
          {report.checks.map(check => {
            const style = STATE_STYLE[check.state]
            const Icon = ICONS[check.id] ?? Server
            return (
              <Card key={check.id} className="h-full">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3">
                    <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary-50 text-primary">
                      <Icon size={20} />
                    </span>
                    <div>
                      <h2 className="text-lg font-extrabold text-slate-900">{displayContent(check.label)}</h2>
                      <p className="mt-1 text-sm leading-6 text-slate-600">{displayContent(check.detail)}</p>
                    </div>
                  </div>
                  <span
                    className={`inline-flex shrink-0 items-center gap-2 rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-[0.12em] ${style.badge}`}
                  >
                    <span className={`h-1.5 w-1.5 rounded-full ${style.dot}`} />
                    {displayContent(style.label)}
                  </span>
                </div>

                {displayContent(check.facts?.length ? (
                  <dl className="mt-5 grid gap-2 rounded-xl border border-slate-100 bg-slate-50 px-4 py-3 sm:grid-cols-2">
                    {check.facts.map(fact => (
                      <div key={`${check.id}-${fact.label}`} className="flex items-baseline justify-between gap-3">
                        <dt className="text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">
                          {displayContent(fact.label)}
                        </dt>
                        <dd className="text-right text-xs font-semibold text-slate-800">{displayContent(fact.value)}</dd>
                      </div>
                    ))}
                  </dl>
                ) : null)}
              </Card>
            )
          })}
        </div>

        <Card className="mt-6">
          <h2 className="flex items-center gap-2 text-lg font-extrabold text-slate-900">
            <ShieldCheck size={18} className="text-gold-600" /> Runtime
          </h2>
          <dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {report.environment.map(item => (
              <div key={item.label} className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3">
                <dt className="text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">
                  {displayContent(item.label)}
                </dt>
                <dd className="mt-1 break-words text-sm font-semibold text-slate-800">{displayContent(item.value)}</dd>
              </div>
            ))}
          </dl>
        </Card>

        <div className="mt-6 rounded-2xl border border-primary-100 bg-white px-6 py-5 shadow-card">
          <h2 className="text-base font-extrabold text-slate-900">What each panel means</h2>
          <ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-600 lg:grid-cols-2">
            <li>
              <strong className="text-slate-800">Database</strong>, the site&rsquo;s content, members,
              applications, orders and certificates. If this is down, nothing else can work.
            </li>
            <li>
              <strong className="text-slate-800">Email delivery</strong>, verification codes and
              receipts. Without SMTP, new sign ups cannot finish verification; that is deliberate.
            </li>
            <li>
              <strong className="text-slate-800">Private storage</strong>, CVs and generated
              certificates, stored outside the public web root and served only to their owner or staff.
            </li>
            <li>
              <strong className="text-slate-800">Payment gateways</strong>, a gateway appears at
              checkout only when its credentials exist, so nothing can silently fake a payment.
            </li>
          </ul>
          <p className="mt-4 text-sm text-slate-600">
            Something looks wrong? Write to{displayContent(' ')}
            <Link href="/contact" className="font-bold text-primary underline decoration-gold-300">
              the secretariat
            </Link>{displayContent(' ')}
            with the time shown above and we can match it against the audit log.
          </p>
        </div>
      </section>
    </div>
  )
}
